"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from '../components/Sidebar'

import { Container, Nav, Navbar } from 'react-bootstrap';
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isOpen, setIsOpen] = useState(true);


  return(
    <html lang="en">
      <body className={inter.className}>
        {/* Pass only the isOpen prop to Sidebar */}
        <Sidebar isOpen={isOpen}></Sidebar>
        
        {/* Children is passed here to render the page content */}
        <div style={{ marginLeft: isOpen ? '240px' : '60px', transition: 'margin-left 0.3s ease', padding: '20px' }}>
          {children}
        </div>
      </body>
    </html>
  );
  
  
}
